/**
 * Prompt Revisions — CRUD operations for prompt optimization proposals
 *
 * Stores proposed prompt improvements generated by the eval optimizer script.
 * Each revision tracks the current prompt, the proposed improvement,
 * a summary of the scores that triggered optimization, and its approval status.
 */

import { mutation, query } from './_generated/server';
import { v } from 'convex/values';

/**
 * Save a new prompt revision proposal.
 * Status is automatically set to "proposed" on creation.
 */
export const save = mutation({
    args: {
        agentId: v.string(),
        currentPrompt: v.string(),
        proposedPrompt: v.string(),
        scoresSummary: v.any(),
        failureCount: v.number(),
        model: v.string(),
    },
    handler: async (ctx, args) => {
        return ctx.db.insert('prompt_revisions', {
            ...args,
            status: 'proposed',
            createdAt: Date.now(),
        });
    },
});

/**
 * Update the status of a prompt revision (e.g., "accepted" or "rejected").
 */
export const updateStatus = mutation({
    args: {
        id: v.id('prompt_revisions'),
        status: v.string(),
    },
    handler: async (ctx, args) => {
        await ctx.db.patch(args.id, { status: args.status });
    },
});

/**
 * List recent prompt revisions for a given agent, newest first.
 * Returns up to 20 revisions.
 */
export const listByAgent = query({
    args: { agentId: v.string() },
    handler: async (ctx, args) => {
        return ctx.db
            .query('prompt_revisions')
            .withIndex('by_agent', (q) => q.eq('agentId', args.agentId))
            .order('desc')
            .take(20);
    },
});
